MessageReplace:
#这个是直接把字符串替换成对应的消息，可以用来做屏蔽词过滤，也可以用来弄快捷发送十六进制颜色
#-是分割符，左边是等待替换的字符串，右边是替换后的字符串。
  - "#浅粉红-<255 182 193>"
  - "#幽白-<248 248 255>"
  - "#绿玉-<127 255 170>"
  - "#深橙-<255 140 0>"
  - "#橙红-<255 69 0>"
  - "#银白-<192 192 192>"
  - "#淡蓝-<135 206 250>"
  - "操你妈-我爱你"
  - "傻逼-小可爱"
#按顺序进行判断，只有上一个判断不满足才会进行下一个判断
FirstFormat:
#第一种格式为#RGB简写，RGB对应的是十六进制字符。
  Begin: "#"
SecondFormat:
  #第二种判断格式为 <R G B> RGB对应三个0~255的整数，可以修改这个格式的前后缀
  Begin: "<"
  Last: ">"